cereal:
    гречка: "12.6/3.3/62.1/313"
    рис: "6.7/0.7/78.9/344"
    геркулес: "11/6.2/48.9/305"
    макароны: "10.1/1.4/71.5/344"

dairy:
    молоко: "3.2/4/5/70"
    творог: "18/0.6/1.8/88"
    йогурт:
        простоквашино_2.5_%: "3/2.5/13.4/88"
        bio_balance_злаки: "3.1/1.5/12.6/76"
        для_всей_семьи: "3.1/2.5/15.1/95"

vegetables:
    томат: "0.6/0.2/4.2/20"

fruits:
    яблоко: "0.4/0.4/9.8/47"
    банан: "1.5/0.1/21.8/89"

nuts:
    арахис_жареный_солёный_viva_nut: "26.3/45.2/9.7/548"
    миндаль_viva_nut: "18.6/53.7/13/609"
    грецкий: "24/59/10/618"

wtf:
    snickers: "7.5/28.5/56/514"
    chocopie: "4/16.1/70.5/440"
    печенье:
        юбилейное_утреннее: "8/14.7/73.4/437"
